export const DATA_TEST_ID = {
    createNewTrainingButton: 'create-new-training-button',
    googleSubmitBtn: 'google-submit-button',
    bigFileErrorClose: 'big-file-error-close',
    alert: 'alert',
    loader: 'loader',
    headerSettings: 'header-settings',
    settingsBack: 'settings-back',

    menuButtonTraining: 'menu-button-training',
    menuButtonCalendar: 'menu-button-calendar',
    menuButtonProfile: 'menu-button-profile',

    modalNoReview: 'modal-no-review',
    modalErrorUserTrainingTitle: 'modal-error-user-training-title',
    modalErrorUserTrainingSubTitle: 'modal-error-user-training-subtitle',
    modalErrorUserTrainingButton: 'modal-error-user-training-button',
    modalErrorUserTrainingButtonClose: 'modal-error-user-training-button-close',
    modalCreateTraining: 'modal-create-training',
    modalCreateTrainingButtonClose: 'modal-create-training-button-close',
    modalUpdateTrainingEditButton: 'modal-update-training-edit-button',
    modalCreateExercise: 'modal-create-exercise',
    modalCreateExerciseButton: 'modal-create-exercise-button',
    modalCreateExerciseSelect: 'modal-create-exercise-select',
    modalExerciseTrainingButtonClose: 'modal-exercise-training-button-close',
    modalDrawerRight: 'modal-drawer-right',
    modalDrawerRightButtonClose: 'modal-drawer-right-button-close',
    modalDrawerRightInputExercise: 'modal-drawer-right-input-exercise',
    modalDrawerRightCheckboxExercise: 'modal-drawer-right-checkbox-exercise',
    modalDrawerRightInputApproach: 'modal-drawer-right-input-approach',
    modalDrawerRightInputWeight: 'modal-drawer-right-input-weight',
    modalDrawerRightInputQuantity: 'modal-drawer-right-input-quantity',
    modalDrawerRightDatePicker: 'modal-drawer-right-date-picker',
    modalDrawerRightCheckboxPeriod: 'modal-drawer-right-checkbox-period',
    modalDrawerRightSelectPeriod: 'modal-drawer-right-select-period',

    myTrainingsTable: 'my-trainings-table',
    updateMyTrainingTableIcon: 'update-my-training-table-icon',
    createTrainingSuccessAlert: 'create-training-success-alert',
    searchInput: 'search-input',
    jointTrainingCards: 'joint-training-cards',
    jointTrainingReviewCard: 'joint-training-review-card',
    notificationAboutJointTraining: 'notification-about-joint-training',
    partnerModal: 'partner-modal',

    profileName: 'profile-name',
    profileSurname: 'profile-surname',
    profileAvatar: 'profile-avatar',
    profilePassword: 'profile-password',
    profileRepeatPassword: 'profile-repeat-password',
    profileEmail: 'profile-email',
    profileBirthday: 'profile-birthday',
    profileSubmit: 'profile-submit',

    tarif: 'tariff-',
    proTarifCard: 'pro-tariff-card',
    activateTariffBtn: 'activate-tariff-btn',
    tariffTrainings: 'tariff-trainings',
    tariffTrainingsIcon: 'tariff-trainings-icon',
    tariffNotifications: 'tariff-notifications',
    tariffNotificationsIcon: 'tariff-notifications-icon',
    tariffTheme: 'tariff-theme',
    tariffThemeIcon: 'tariff-theme-icon',
    tariffSider: 'tariff-sider',
    tariffCost: 'tariff-cost',
    tariffSubmit: 'tariff-submit',
    tariffModalSuccess: 'tariff-modal-success',

    loginEmail: 'login-email',
    loginPassword: 'login-password',
    loginSubmitBtn: 'login-submit-button',
    loginRetryBtn: 'login-retry-button',
    loginRemember: 'login-remember',

    seeReview: 'see-reviews',
    writeReview: 'write-review',
    allReviewBtn: 'all-reviews-button',
    writeReviewNotSavedModal: 'write-review-not-saved-modal',
    newReviewSubmitBtn: 'new-review-submit-button',

    registrationEmail: 'registration-email',
    registrationPassword: 'registration-password',
    registrationConfirmPassword: 'registration-confirm-password',
    registrationSubmitBtn: 'registration-submit-button',
    registrationEnterBtn: 'registration-enter-button',
    checkBackBtn: 'check-back-button',
    registrationBackBtn: 'registration-back-button',
    loginForgotBtn: 'login-forgot-button',
    verificationInput: 'verification-input',
    changePassword: 'change-password',
    changeConformPassword: 'change-confirm-password',
    changeSubmitBtn: 'change-submit-button',
    changeEntryBtn: 'change-entry-button',
    checkRetryBtn: 'check-retry-button',
    changeRetryBtn: 'change-retry-button',

    siderSwitch: 'sider-switch',
    siderSwitchMobile: 'sider-switch-mobile',
    sidebarAchievements: 'sidebar-achievements',
};
